/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pets;

import config.dbConnector;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;

public class addpet extends javax.swing.JFrame {

    private String selectedImagePath = null;

    public addpet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        petname = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        imagepathlabel = new javax.swing.JLabel();
        species = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        breedfield = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        addPet = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        selectPetImage = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        color = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        gender = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(142, 177, 217));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Add Pet");
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 500, -1));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 60));

        petname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        petname.setPreferredSize(new java.awt.Dimension(350, 40));
        jPanel7.add(petname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 160, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Pet Name");
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 70, -1));

        imagepathlabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        imagepathlabel.setText("Image Path:");
        jPanel7.add(imagepathlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 150, -1));

        species.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        species.setPreferredSize(new java.awt.Dimension(350, 40));
        jPanel7.add(species, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 160, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Species");
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));

        breedfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        breedfield.setPreferredSize(new java.awt.Dimension(350, 40));
        jPanel7.add(breedfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 160, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Breed");
        jPanel7.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        addPet.setBackground(new java.awt.Color(46, 134, 222));
        addPet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addPet.setText("Add");
        addPet.setBorder(null);
        addPet.setPreferredSize(new java.awt.Dimension(350, 40));
        addPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPetActionPerformed(evt);
            }
        });
        jPanel7.add(addPet, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 310, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Gender");
        jPanel7.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 70, -1));

        age.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        age.setPreferredSize(new java.awt.Dimension(350, 40));
        jPanel7.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 160, -1));

        selectPetImage.setBackground(new java.awt.Color(142, 177, 217));
        selectPetImage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectPetImage.setText("Select Image");
        selectPetImage.setBorder(null);
        selectPetImage.setPreferredSize(new java.awt.Dimension(350, 40));
        selectPetImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectPetImageActionPerformed(evt);
            }
        });
        jPanel7.add(selectPetImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 150, 40));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("Age");
        jPanel7.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, -1));

        color.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        color.setPreferredSize(new java.awt.Dimension(350, 40));
        jPanel7.add(color, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 160, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setText("Color");
        jPanel7.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 70, -1));

        gender.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Gender", "Male", "Female", " ", " " }));
        gender.setPreferredSize(new java.awt.Dimension(350, 40));
        jPanel7.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 160, 40));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addPetActionPerformed(java.awt.event.ActionEvent evt) {
        // Validate fields
        String name = petname.getText().trim();
        String sp = species.getText().trim();
        String breed = breedfield.getText().trim();
        String ageStr = age.getText().trim();
        String genderStr = gender.getSelectedItem().toString();
        String colorStr = color.getText().trim();
        String statusStr = "Available";
        String imagePath = selectedImagePath;
        if (imagePath == null || imagePath.isEmpty()) {
            imagePath = "src/images/petdefault.png";
        }

        // Validation
        if (name.isEmpty() || sp.isEmpty() || breed.isEmpty() || ageStr.isEmpty() || 
            colorStr.isEmpty() || gender.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields!");
            return;
        }

        int ageVal = 0;
        try {
            ageVal = Integer.parseInt(ageStr);
            if (ageVal <= 0) throw new NumberFormatException();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Age must be a positive integer.");
            return;
        }

        // Copy image if not default
        String dbImagePath = imagePath;
        if (!imagePath.equals("src/images/petdefault.png")) {
            try {
                File srcFile = new File(imagePath);
                String destPath = "src/images/" + srcFile.getName();
                File destFile = new File(destPath);
                Files.copy(srcFile.toPath(), destFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
                dbImagePath = destPath;
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Failed to copy image: " + ex.getMessage());
                return;
            }
        }

        try {
            // Insert into DB using PreparedStatement
            dbConnector dbc = new dbConnector();
            String sql = "INSERT INTO pets (name, species, breed, age, gender, color, status, image_path) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
            java.sql.PreparedStatement pst = dbc.getConnection().prepareStatement(sql);
            pst.setString(1, name);
            pst.setString(2, sp);
            pst.setString(3, breed);
            pst.setInt(4, ageVal);
            pst.setString(5, genderStr);
            pst.setString(6, colorStr);
            pst.setString(7, statusStr);
            pst.setString(8, dbImagePath);
            
            int result = pst.executeUpdate();
            if (result > 0) {
                JOptionPane.showMessageDialog(this, "Pet added successfully!");
                this.dispose();
              
            } else {
                JOptionPane.showMessageDialog(this, "Failed to add pet!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error adding pet: " + ex.getMessage());
        }
    }

    private void selectPetImageActionPerformed(java.awt.event.ActionEvent evt) {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Image Files", "jpg", "jpeg", "png", "gif"));
        
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            selectedImagePath = selectedFile.getAbsolutePath();
            imagepathlabel.setText(selectedFile.getName());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addpet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addpet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addpet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addpet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addpet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPet;
    private javax.swing.JTextField age;
    private javax.swing.JTextField breedfield;
    private javax.swing.JTextField color;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JLabel imagepathlabel;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField petname;
    private javax.swing.JButton selectPetImage;
    private javax.swing.JTextField species;
    // End of variables declaration//GEN-END:variables
}
