/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pets;

import config.dbConnector;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import java.awt.Image;

public class viewpet extends javax.swing.JFrame {

    public viewpet(int petId) {
        initComponents();
        loadPetDetails(petId);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        petimage = new javax.swing.JLabel();
        editpet = new javax.swing.JButton();
        petimage1 = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        Species = new javax.swing.JLabel();
        breed = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        age = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(142, 177, 217));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Pet Viewing");
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 500, -1));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 60));

        petimage.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        petimage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.add(petimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 190, 150));

        editpet.setBackground(new java.awt.Color(46, 134, 222));
        editpet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        editpet.setText("Back");
        editpet.setBorder(null);
        editpet.setPreferredSize(new java.awt.Dimension(350, 40));
        editpet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editpetActionPerformed(evt);
            }
        });
        jPanel7.add(editpet, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 310, -1));

        petimage1.setBackground(new java.awt.Color(0, 153, 255));
        petimage1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        petimage1.setForeground(new java.awt.Color(0, 153, 255));
        petimage1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        petimage1.setText("Name");
        jPanel7.add(petimage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 190, 30));

        status.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        status.setForeground(new java.awt.Color(0, 153, 255));
        status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        status.setText("Status");
        jPanel7.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 190, 30));

        Species.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Species.setForeground(new java.awt.Color(0, 0, 0));
        Species.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Species.setText("Species");
        jPanel7.add(Species, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 190, 30));

        breed.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        breed.setForeground(new java.awt.Color(0, 0, 0));
        breed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        breed.setText("Species");
        jPanel7.add(breed, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 190, 30));

        gender.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gender.setForeground(new java.awt.Color(0, 0, 0));
        gender.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gender.setText("Species");
        jPanel7.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 190, 30));

        age.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        age.setForeground(new java.awt.Color(0, 0, 0));
        age.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        age.setText("Species");
        jPanel7.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 190, 30));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void editpetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editpetActionPerformed
     
      this.dispose();
    }//GEN-LAST:event_editpetActionPerformed

    private void loadPetDetails(int petId) {
        try {
            dbConnector dbc = new dbConnector();
            String query = "SELECT * FROM pets WHERE pet_id = ?";
            PreparedStatement pst = dbc.getConnection().prepareStatement(query);
            pst.setInt(1, petId);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                petimage1.setText(rs.getString("name"));
                Species.setText("Species: " + rs.getString("species"));
                breed.setText("Breed: " + rs.getString("breed"));
                age.setText("Age: " + rs.getInt("age"));
                gender.setText("Gender: " + rs.getString("gender"));
                status.setText("Status: " + rs.getString("status"));
                String imagePath = rs.getString("image_path");
                if (imagePath == null || imagePath.trim().isEmpty()) {
                    imagePath = "src/images/petdefault.png";
                }
                ImageIcon icon = new ImageIcon(imagePath);
                Image img = icon.getImage().getScaledInstance(190, 150, Image.SCALE_SMOOTH);
                petimage.setIcon(new ImageIcon(img));
            }
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error loading pet details: " + ex.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Species;
    private javax.swing.JLabel age;
    private javax.swing.JLabel breed;
    private javax.swing.JButton editpet;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel petimage;
    private javax.swing.JLabel petimage1;
    private javax.swing.JLabel status;
    // End of variables declaration//GEN-END:variables
}
