/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;

import config.Session;
import config.dbConnector;
import config.passwordHasher;
import java.awt.Color;
import java.io.File;
import java.sql.ResultSet;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.netbeans.lib.awtextra.AbsoluteLayout;
import racazagui.login;

/**
 *
 * @author johnlloyd
 */
public class AccountDetails extends javax.swing.JFrame {

    // Add method to update image path in database
    private void updateUserImagePath(int userId, String imagePath) {
        try {
            dbConnector dbc = new dbConnector();
            String updateQuery = "UPDATE tbl_user SET image = '" + imagePath + "' WHERE u_id = '" + userId + "'";
            dbc.updateData(updateQuery);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error updating image path in database: " + ex.getMessage());
        }
    }

    // Utility method to set profile image with fallback (now uses userprofile label)
    private void setProfileImage(String imageFileName) {
        String basePath = "src/images/";
        String imagePath = basePath + (imageFileName != null ? imageFileName : "");
        java.io.File imgFile = new java.io.File(imagePath);
        config.profile prof = new config.profile();
        if (imgFile.exists() && imgFile.isFile()) {
            userprofile.setIcon(prof.ResizeImage(imagePath, null, userprofile));
        } else {
            userprofile.setIcon(prof.ResizeImage(basePath + "defaultimage.png", null, userprofile));
        }
    }

    /**
     * Creates new form userDashboard
     */
    public AccountDetails() {
        initComponents();
      
    }
  private static final Color black = new Color (0,0,0);
  private static final Color white = new Color (240,240,240);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        userprofile = new javax.swing.JLabel();
        acc_lname = new javax.swing.JLabel();
        acc_fname = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        changepassword = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        resfntext = new javax.swing.JLabel();
        firstnamef = new javax.swing.JTextField();
        reslntext = new javax.swing.JLabel();
        lastnamef = new javax.swing.JTextField();
        resemailtext = new javax.swing.JLabel();
        emailf = new javax.swing.JTextField();
        resusrntext = new javax.swing.JLabel();
        usernamef = new javax.swing.JTextField();
        accountypecombobox = new javax.swing.JComboBox<>();
        imagePath = new javax.swing.JLabel();
        iddisplay = new javax.swing.JLabel();
        WELCOME4 = new javax.swing.JLabel();
        saveInfo = new javax.swing.JButton();
        selectimage = new javax.swing.JButton();
        attext1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 102));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(123, 159, 207));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(123, 159, 207));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userprofile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/defaultimage.png"))); // NOI18N
        jPanel3.add(userprofile, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 14, -1, -1));

        acc_lname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        acc_lname.setForeground(new java.awt.Color(255, 255, 255));
        acc_lname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_lname.setText("User");
        jPanel3.add(acc_lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 242, -1));

        acc_fname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        acc_fname.setForeground(new java.awt.Color(255, 255, 255));
        acc_fname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_fname.setText("User");
        jPanel3.add(acc_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 158, 242, 29));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LOGOUT");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 280, 50));

        changepassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        changepassword.setForeground(new java.awt.Color(255, 255, 255));
        changepassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        changepassword.setText("CHANGE PASSWORD");
        changepassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changepasswordMouseClicked(evt);
            }
        });
        jPanel2.add(changepassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 280, 50));

        back.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setText("BACK");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        jPanel2.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 280, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 750));

        resfntext.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        resfntext.setForeground(new java.awt.Color(0, 0, 0));
        resfntext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resfntext.setText("First Name:");
        jPanel1.add(resfntext, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 340, 30));

        firstnamef.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        firstnamef.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        firstnamef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnamefActionPerformed(evt);
            }
        });
        jPanel1.add(firstnamef, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 340, 40));

        reslntext.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        reslntext.setForeground(new java.awt.Color(0, 0, 0));
        reslntext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reslntext.setText("Last Name:");
        jPanel1.add(reslntext, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 340, 30));

        lastnamef.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lastnamef.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lastnamef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnamefActionPerformed(evt);
            }
        });
        jPanel1.add(lastnamef, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 340, 40));

        resemailtext.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        resemailtext.setForeground(new java.awt.Color(0, 0, 0));
        resemailtext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resemailtext.setText("Email:");
        jPanel1.add(resemailtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 340, 30));

        emailf.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        emailf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emailf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailfActionPerformed(evt);
            }
        });
        jPanel1.add(emailf, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 340, 40));

        resusrntext.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        resusrntext.setForeground(new java.awt.Color(0, 0, 0));
        resusrntext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resusrntext.setText("Username:");
        jPanel1.add(resusrntext, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 340, 30));

        usernamef.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        usernamef.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usernamef.setEnabled(false);
       
        jPanel1.add(usernamef, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 340, 40));

        accountypecombobox.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        accountypecombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User", "Admin" }));
        accountypecombobox.setEnabled(false);
        accountypecombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountypecomboboxActionPerformed(evt);
            }
        });
        jPanel1.add(accountypecombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 340, 50));

        imagePath.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        imagePath.setForeground(new java.awt.Color(0, 0, 0));
        imagePath.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagePath.setText("image: ");
        jPanel1.add(imagePath, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 190, 50));

        iddisplay.setFont(new java.awt.Font("HP Simplified Jpan", 1, 24)); // NOI18N
        iddisplay.setForeground(new java.awt.Color(255, 255, 255));
        iddisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iddisplay.setText("(UID)");
        jPanel1.add(iddisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 160, 60));

        WELCOME4.setFont(new java.awt.Font("HP Simplified Jpan", 0, 24)); // NOI18N
        WELCOME4.setForeground(new java.awt.Color(255, 255, 255));
        WELCOME4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WELCOME4.setText("ACCOUNT INFORMATION");
        jPanel1.add(WELCOME4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 440, 70));

        saveInfo.setBackground(new java.awt.Color(102, 153, 255));
        saveInfo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        saveInfo.setForeground(new java.awt.Color(0, 0, 0));
        saveInfo.setText("Save");
        saveInfo.setBorder(null);
        saveInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveInfoMouseClicked(evt);
            }
        });
        saveInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveInfoActionPerformed(evt);
            }
        });
        jPanel1.add(saveInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 660, 340, 50));

        selectimage.setBackground(new java.awt.Color(102, 153, 255));
        selectimage.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        selectimage.setForeground(new java.awt.Color(0, 0, 0));
        selectimage.setText("Select Image");
        selectimage.setBorder(null);
        selectimage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectimageMouseClicked(evt);
            }
        });
        selectimage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectimageActionPerformed(evt);
            }
        });
        jPanel1.add(selectimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, 140, 50));

        attext1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        attext1.setForeground(new java.awt.Color(0, 0, 0));
        attext1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        attext1.setText("Account Type:");
        jPanel1.add(attext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 340, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Session sess = Session.getInstance();
        iddisplay.setText("USER ID:" + sess.getUid());
        firstnamef.setText("" + sess.getFname());
        lastnamef.setText("" + sess.getLname());
        emailf.setText("" + sess.getEmail());
        usernamef.setText(sess.getUsername() != null ? sess.getUsername() : "");

        
        if (sess.getUid() == 0) {
            JOptionPane.showMessageDialog(null, "No Account, Log in First!");
            login lg = new login();
            lg.setVisible(true);
            this.dispose();
        } else {
            acc_fname.setText("" + sess.getFname());
            acc_lname.setText("" + sess.getLname());
            // Display user image if available, fallback to default, using userprofile label
            setProfileImage(sess.getImage());
            imagePath.setText("Image: " + (sess.getImage() != null ? sess.getImage() : "defaultimage.png"));
        }
    }//GEN-LAST:event_formWindowActivated

    private void firstnamefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnamefActionPerformed
        String firstName = firstnamef.getText();  // ✅ Correct

    }//GEN-LAST:event_firstnamefActionPerformed

    private void lastnamefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnamefActionPerformed
        String lastName = lastnamef.getText();  // ✅ Correct
    }//GEN-LAST:event_lastnamefActionPerformed

    private void emailfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailfActionPerformed
        String email = emailf.getText().trim();  // ✅ Correct
        dbConnector dbc = new dbConnector();
    }//GEN-LAST:event_emailfActionPerformed


    private void accountypecomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountypecomboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountypecomboboxActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        new login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void changepasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changepasswordMouseClicked
       changepass cp = new changepass();
       cp.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_changepasswordMouseClicked

    private void saveInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveInfoMouseClicked

    }//GEN-LAST:event_saveInfoMouseClicked

    private void saveInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveInfoActionPerformed
        try {
            String newFname = firstnamef.getText().trim();
            String newLname = lastnamef.getText().trim();
            String newEmail = emailf.getText().trim();
            Session sess = Session.getInstance();

            if (newFname.isEmpty() || newLname.isEmpty() || newEmail.isEmpty()) {
                JOptionPane.showMessageDialog(null, "First name, last name, and email cannot be empty.");
                return;
            }

            dbConnector dbc = new dbConnector();
            String updateQuery = "UPDATE tbl_user SET u_firstname = '" + newFname + "', u_lastname = '" + newLname + "', u_email = '" + newEmail + "', image = '" + sess.getImage() + "' WHERE u_id = '" + sess.getUid() + "'";
            dbc.updateData(updateQuery);

            // Update session data
            sess.setFname(newFname);
            sess.setLname(newLname);
            sess.setEmail(newEmail);

            JOptionPane.showMessageDialog(null, "Information updated successfully.");

            // Refresh displayed data
            firstnamef.setText(newFname);
            lastnamef.setText(newLname);
            emailf.setText(newEmail);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error updating information: " + ex.getMessage());
        }
    }//GEN-LAST:event_saveInfoActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
       new userDashboard().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void selectimageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectimageMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_selectimageMouseClicked

    private void selectimageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectimageActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Image files", "jpg", "jpeg", "png", "gif"));
        
        int returnValue = fileChooser.showOpenDialog(this);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            try {
                File selectedFile = fileChooser.getSelectedFile();
                if (!selectedFile.exists() || !selectedFile.isFile()) {
                    JOptionPane.showMessageDialog(this, "Selected file does not exist.");
                    return;
                }

                // Create images directory if it doesn't exist
                String imagesDirPath = "src/images";
                File imagesDir = new File(imagesDirPath);
                if (!imagesDir.exists()) {
                    boolean created = imagesDir.mkdirs();
                    if (!created) {
                        JOptionPane.showMessageDialog(this, "Failed to create images directory.");
                        return;
                    }
                }

                // Generate unique filename to avoid conflicts
                String fileName = System.currentTimeMillis() + "_" + selectedFile.getName().replaceAll("[\\s]+", "_");
                String destination = imagesDirPath + File.separator + fileName;
                
                // Copy the file first
                try {
                    config.profile prof = new config.profile();
                    prof.imageUpdater(destination, selectedFile.getAbsolutePath());
                    
                    // Set the image icon only after successful copy
                    userprofile.setIcon(prof.ResizeImage(destination, null, userprofile));

                    // Update user's image path in database and session
                config.Session session = config.Session.getInstance();
                    
                // Update image path in database (store only filename)
                updateUserImagePath(session.getUid(), fileName);
                    
                // Update session
                session.setImage(fileName);

                    JOptionPane.showMessageDialog(this, "Profile picture updated successfully!");
                } catch (Exception copyEx) {
                    JOptionPane.showMessageDialog(this, "Error copying image file: " + copyEx.getMessage());
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error updating profile picture: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_selectimageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel WELCOME4;
    private javax.swing.JLabel acc_fname;
    private javax.swing.JLabel acc_lname;
    private javax.swing.JComboBox<String> accountypecombobox;
    private javax.swing.JLabel attext1;
    private javax.swing.JLabel back;
    private javax.swing.JLabel changepassword;
    private javax.swing.JTextField emailf;
    private javax.swing.JTextField firstnamef;
    private javax.swing.JLabel iddisplay;
    private javax.swing.JLabel imagePath;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField lastnamef;
    private javax.swing.JLabel resemailtext;
    private javax.swing.JLabel resfntext;
    private javax.swing.JLabel reslntext;
    private javax.swing.JLabel resusrntext;
    private javax.swing.JButton saveInfo;
    private javax.swing.JButton selectimage;
    private javax.swing.JTextField usernamef;
    private javax.swing.JLabel userprofile;
    // End of variables declaration//GEN-END:variables
}
