/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;

import admin.admindashboard;
import javax.swing.JOptionPane;
import pets.viewpet;
import config.dbConnector;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;


public class userpetadopt extends javax.swing.JFrame {

   
    public userpetadopt() {
        initComponents();
        loadAvailablePets();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        acc_id = new javax.swing.JLabel();
        jlabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        backbtn = new javax.swing.JLabel();
        WELCOME3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        petstable = new javax.swing.JTable();
        viewpet = new javax.swing.JButton();
        adoptpet = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(142, 177, 217));
        background.setForeground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(123, 159, 207));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        acc_id.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        acc_id.setForeground(new java.awt.Color(255, 255, 255));
        acc_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_id.setText("ID");
        jPanel2.add(acc_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 801, 280, 42));

        jlabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jlabel.setForeground(new java.awt.Color(255, 255, 255));
        jlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabel.setText("Current User:");
        jPanel2.add(jlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 738, 280, 45));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LOGOUT");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 663, 280, 44));

        backbtn.setBackground(new java.awt.Color(142, 177, 217));
        backbtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        backbtn.setForeground(new java.awt.Color(255, 255, 255));
        backbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backbtn.setText("BACK");
        backbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbtnMouseClicked(evt);
            }
        });
        jPanel2.add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 280, 45));

        WELCOME3.setFont(new java.awt.Font("HP Simplified Jpan", 0, 24)); // NOI18N
        WELCOME3.setForeground(new java.awt.Color(255, 255, 255));
        WELCOME3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WELCOME3.setText("PET'S PAGE");
        jPanel2.add(WELCOME3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 280, 70));

        background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 650));

        petstable.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        petstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(petstable);

        background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 640, 400));

        viewpet.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        viewpet.setText("View Pet");
        viewpet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewpetMouseClicked(evt);
            }
        });
        viewpet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewpetActionPerformed(evt);
            }
        });
        background.add(viewpet, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 100, 140, 50));

        adoptpet.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        adoptpet.setText("Adopt a Pet");
        adoptpet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adoptpetMouseClicked(evt);
            }
        });
        adoptpet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adoptpetActionPerformed(evt);
            }
        });
        background.add(adoptpet, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 140, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked

    }//GEN-LAST:event_jLabel2MouseClicked

    private void backbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbtnMouseClicked
        new userDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backbtnMouseClicked

    private void viewpetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewpetMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_viewpetMouseClicked

    private void viewpetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewpetActionPerformed
        int selectedRow = petstable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a pet to view!");
            return;
        }
        int petId = Integer.parseInt(petstable.getValueAt(selectedRow, 0).toString());
        new viewpet(petId).setVisible(true);
    }//GEN-LAST:event_viewpetActionPerformed

    private void adoptpetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adoptpetMouseClicked

    }//GEN-LAST:event_adoptpetMouseClicked

    private void adoptpetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adoptpetActionPerformed
        int selectedRow = petstable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a pet to adopt!");
            return;
        }
        String status = petstable.getValueAt(selectedRow, 7).toString();
        if (status.equals("Pending Adoption Approval")) {
            JOptionPane.showMessageDialog(this, "This pet is already pending adoption approval.");
            return;
        }
        if (status.equals("Adopted")) {
            JOptionPane.showMessageDialog(this, "This pet has already been adopted.");
            return;
        }
        int petId = Integer.parseInt(petstable.getValueAt(selectedRow, 0).toString());
        new adoption.adoptpet(petId).setVisible(true);
    }//GEN-LAST:event_adoptpetActionPerformed

    private void loadAvailablePets() {
        String[] columns = {"ID", "Name", "Species", "Breed", "Age", "Gender", "Color", "Status"};
        DefaultTableModel model = new DefaultTableModel(null, columns) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        try {
            dbConnector dbc = new dbConnector();
            ResultSet rs = dbc.getData("SELECT * FROM pets WHERE status = 'Available'");
            while (rs.next()) {
                model.addRow(new Object[] {
                    rs.getInt("pet_id"),
                    rs.getString("name"),
                    rs.getString("species"),
                    rs.getString("breed"),
                    rs.getInt("age"),
                    rs.getString("gender"),
                    rs.getString("color"),
                    rs.getString("status")
                });
            }
            petstable.setModel(model);
            petstable.setRowHeight(40);

            if (model.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "No pets are currently available for adoption.");
                adoptpet.setEnabled(false);
            } else {
                adoptpet.setEnabled(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading pets: " + e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userpetadopt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userpetadopt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userpetadopt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userpetadopt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userpetadopt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel WELCOME3;
    private javax.swing.JLabel acc_id;
    private javax.swing.JButton adoptpet;
    private javax.swing.JLabel backbtn;
    private javax.swing.JPanel background;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlabel;
    private javax.swing.JTable petstable;
    private javax.swing.JButton viewpet;
    // End of variables declaration//GEN-END:variables
}
