/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adoption;

import config.dbConnector;
import config.Session;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDate;
import javax.swing.ImageIcon;
import java.awt.Image;
import javax.swing.JOptionPane;


public class adoptpet extends javax.swing.JFrame {

    private int petId;

   private static Session ses = new Session();
    public adoptpet() {
        initComponents();
    }

    public adoptpet(int petId) {
        this.petId = petId;
        initComponents();
        loadPetDetails(petId);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        petimage = new javax.swing.JLabel();
        adopt = new javax.swing.JButton();
        petimage1 = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        Species = new javax.swing.JLabel();
        breed = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        age = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(142, 177, 217));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Adopt Pet");
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 500, -1));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 60));

        petimage.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        petimage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.add(petimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 190, 150));

        adopt.setBackground(new java.awt.Color(46, 134, 222));
        adopt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        adopt.setText("Adopt");
        adopt.setBorder(null);
        adopt.setPreferredSize(new java.awt.Dimension(350, 40));
        adopt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adoptActionPerformed(evt);
            }
        });
        jPanel7.add(adopt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 310, -1));

        petimage1.setBackground(new java.awt.Color(0, 153, 255));
        petimage1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        petimage1.setForeground(new java.awt.Color(0, 153, 255));
        petimage1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        petimage1.setText("Name");
        jPanel7.add(petimage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 190, 30));

        status.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        status.setForeground(new java.awt.Color(0, 153, 255));
        status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        status.setText("Status");
        jPanel7.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 190, 30));

        Species.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Species.setForeground(new java.awt.Color(0, 0, 0));
        Species.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Species.setText("Species");
        jPanel7.add(Species, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 190, 30));

        breed.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        breed.setForeground(new java.awt.Color(0, 0, 0));
        breed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        breed.setText("Species");
        jPanel7.add(breed, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 190, 30));

        gender.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gender.setForeground(new java.awt.Color(0, 0, 0));
        gender.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gender.setText("Species");
        jPanel7.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 190, 30));

        age.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        age.setForeground(new java.awt.Color(0, 0, 0));
        age.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        age.setText("Species");
        jPanel7.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 190, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void adoptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adoptActionPerformed
        try {
            // Get the current user ID from the session
            int adopterId = Session.getInstance().getUid();
            if (adopterId == 0) {
                JOptionPane.showMessageDialog(this, "No user logged in. Please log in first.");
                return;
            }
            dbConnector dbc = new dbConnector();
            
            // First update the pet's status to Pending Adoption Approval
            String updatePetQuery = "UPDATE pets SET status = 'Pending Adoption Approval' WHERE pet_id = ?";
            java.sql.PreparedStatement updatePetStmt = dbc.getConnection().prepareStatement(updatePetQuery);
            updatePetStmt.setInt(1, petId);
            int petResult = updatePetStmt.executeUpdate();
            
            if (petResult > 0) {
                // Then insert the adoption record
                String sql = "INSERT INTO adoption_records (adopter_id, pet_id, adoption_date, status) VALUES (?, ?, CURDATE(), 'Pending')";
                java.sql.PreparedStatement pst = dbc.getConnection().prepareStatement(sql);
                pst.setInt(1, adopterId);
                pst.setInt(2, petId);
                int result = pst.executeUpdate();
                
                if (result > 0) {
                    JOptionPane.showMessageDialog(this, "Adoption request submitted successfully! Please wait for admin approval.");
                    this.dispose();
                } else {
                    // If adoption record insertion fails, revert pet status
                    String revertPetQuery = "UPDATE pets SET status = 'Available' WHERE pet_id = ?";
                    java.sql.PreparedStatement revertPetStmt = dbc.getConnection().prepareStatement(revertPetQuery);
                    revertPetStmt.setInt(1, petId);
                    revertPetStmt.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Failed to submit adoption request!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Failed to update pet status!");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error submitting adoption request: " + ex.getMessage());
        }
    }//GEN-LAST:event_adoptActionPerformed

    private void loadPetDetails(int petId) {
        try {
            dbConnector dbc = new dbConnector();
            String query = "SELECT * FROM pets WHERE pet_id = ?";
            PreparedStatement pst = dbc.getConnection().prepareStatement(query);
            pst.setInt(1, petId);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                petimage1.setText(rs.getString("name"));
                Species.setText("Species: " + rs.getString("species"));
                breed.setText("Breed: " + rs.getString("breed"));
                age.setText("Age: " + rs.getInt("age"));
                gender.setText("Gender: " + rs.getString("gender"));
                status.setText("Status: " + rs.getString("status"));
                String imagePath = rs.getString("image_path");
                if (imagePath == null || imagePath.trim().isEmpty()) {
                    imagePath = "src/images/petdefault.png";
                }
                ImageIcon icon = new ImageIcon(imagePath);
                Image img = icon.getImage().getScaledInstance(190, 150, Image.SCALE_SMOOTH);
                petimage.setIcon(new ImageIcon(img));
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error loading pet details: " + ex.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adoptpet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adoptpet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adoptpet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adoptpet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adoptpet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Species;
    private javax.swing.JButton adopt;
    private javax.swing.JLabel age;
    private javax.swing.JLabel breed;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel petimage;
    private javax.swing.JLabel petimage1;
    private javax.swing.JLabel status;
    // End of variables declaration//GEN-END:variables
}
