/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adoption;


public class certificates extends javax.swing.JFrame {

    /**
     * Creates new form certificates
     */
    public certificates() {
        initComponents();
    }

    public void setAdopterName(String name) {
        adoptername.setText(name);
    }

    public void setAdoptionDate(String date) {
        adoptiondate.setText(date);
    }

    public void setPetName(String name) {
        petsname.setText(name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adoptername = new javax.swing.JLabel();
        adoptiondate = new javax.swing.JLabel();
        petsname = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        certificate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adoptername.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        adoptername.setForeground(new java.awt.Color(0, 0, 0));
        adoptername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adoptername.setText("adoptername");
        getContentPane().add(adoptername, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 290, 40));

        adoptiondate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        adoptiondate.setForeground(new java.awt.Color(0, 0, 0));
        adoptiondate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adoptiondate.setText("adoptiondate");
        getContentPane().add(adoptiondate, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, 120, 40));

        petsname.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        petsname.setForeground(new java.awt.Color(0, 0, 0));
        petsname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        petsname.setText("Pet's Name");
        getContentPane().add(petsname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 510, 40));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        certificate.setForeground(new java.awt.Color(0, 0, 0));
        certificate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/certificate.png"))); // NOI18N
        jPanel1.add(certificate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(certificates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(certificates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(certificates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(certificates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new certificates().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adoptername;
    private javax.swing.JLabel adoptiondate;
    private javax.swing.JLabel certificate;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JLabel petsname;
    // End of variables declaration//GEN-END:variables
}
