/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adoption;


public class viewadoption extends javax.swing.JFrame {

    private int adoptionId;

    /**
     * Creates new form viewadoption
     */
    public viewadoption() {
        initComponents();
    }

    public viewadoption(int adoptionId) {
        this.adoptionId = adoptionId;
        initComponents();
        loadAdoptionDetails(adoptionId);
    }

    private void loadAdoptionDetails(int adoptionId) {
        try {
            config.dbConnector dbc = new config.dbConnector();
            String query = "SELECT a.adoption_id, a.adoption_date, a.status, " +
                           "p.name as pet_name, p.species, p.image_path, " +
                           "CONCAT(u.u_firstname, ' ', u.u_lastname) as adopter_name " +
                           "FROM adoption_records a " +
                           "JOIN pets p ON a.pet_id = p.pet_id " +
                           "JOIN tbl_user u ON a.adopter_id = u.u_id " +
                           "WHERE a.adoption_id = ?";
            java.sql.PreparedStatement pst = dbc.getConnection().prepareStatement(query);
            pst.setInt(1, adoptionId);
            java.sql.ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                petimage1.setText(rs.getString("pet_name"));
                Species.setText("Species: " + rs.getString("species"));
                status.setText("Status: " + rs.getString("status"));
                adoptionname.setText("Adopter: " + rs.getString("adopter_name"));
                adoptiondate.setText("Adoption Date: " + rs.getString("adoption_date"));
                String imagePath = rs.getString("image_path");
                if (imagePath == null || imagePath.trim().isEmpty()) {
                    imagePath = "src/images/petdefault.png";
                }
                javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imagePath);
                java.awt.Image img = icon.getImage().getScaledInstance(190, 150, java.awt.Image.SCALE_SMOOTH);
                petimage.setIcon(new javax.swing.ImageIcon(img));
            }
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error loading adoption details: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        petimage = new javax.swing.JLabel();
        editpet = new javax.swing.JButton();
        petimage1 = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        Species = new javax.swing.JLabel();
        adoptionname = new javax.swing.JLabel();
        adoptiondate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(142, 177, 217));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Pet Viewing");
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 500, -1));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 60));

        petimage.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        petimage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.add(petimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 190, 150));

        editpet.setBackground(new java.awt.Color(46, 134, 222));
        editpet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        editpet.setText("Back");
        editpet.setBorder(null);
        editpet.setPreferredSize(new java.awt.Dimension(350, 40));
        editpet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editpetActionPerformed(evt);
            }
        });
        jPanel7.add(editpet, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 310, -1));

        petimage1.setBackground(new java.awt.Color(0, 153, 255));
        petimage1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        petimage1.setForeground(new java.awt.Color(0, 153, 255));
        petimage1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        petimage1.setText("Name");
        jPanel7.add(petimage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 190, 30));

        status.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        status.setForeground(new java.awt.Color(0, 153, 255));
        status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        status.setText("Status");
        jPanel7.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 190, 30));

        Species.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Species.setForeground(new java.awt.Color(0, 0, 0));
        Species.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Species.setText("Species");
        jPanel7.add(Species, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 190, 30));

        adoptionname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        adoptionname.setForeground(new java.awt.Color(0, 0, 0));
        adoptionname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adoptionname.setText("Adopter Name");
        jPanel7.add(adoptionname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 190, 30));

        adoptiondate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        adoptiondate.setForeground(new java.awt.Color(0, 0, 0));
        adoptiondate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adoptiondate.setText("Adoption Date");
        jPanel7.add(adoptiondate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 190, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void editpetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editpetActionPerformed

        this.dispose();
    }//GEN-LAST:event_editpetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewadoption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewadoption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewadoption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewadoption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewadoption().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Species;
    private javax.swing.JLabel adoptiondate;
    private javax.swing.JLabel adoptionname;
    private javax.swing.JButton editpet;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel petimage;
    private javax.swing.JLabel petimage1;
    private javax.swing.JLabel status;
    // End of variables declaration//GEN-END:variables
}
