/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package racazagui;


public class emailverification extends javax.swing.JFrame {

    
    public emailverification() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        verify = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sendcode = new javax.swing.JButton();
        code = new javax.swing.JTextField();
        email = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(142, 177, 217));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Email Verification");
        jPanel10.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 500, 48));

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 60));

        verify.setBackground(new java.awt.Color(204, 204, 255));
        verify.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        verify.setForeground(new java.awt.Color(0, 0, 0));
        verify.setText("Submit");
        verify.setBorder(null);
        verify.setPreferredSize(new java.awt.Dimension(350, 40));
        verify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyActionPerformed(evt);
            }
        });
        jPanel9.add(verify, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 320, -1));

        jLabel1.setText("Code");
        jPanel9.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        jLabel2.setText("Email");
        jPanel9.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        sendcode.setBackground(new java.awt.Color(204, 204, 255));
        sendcode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sendcode.setForeground(new java.awt.Color(0, 0, 0));
        sendcode.setText("Send");
        sendcode.setBorder(null);
        sendcode.setPreferredSize(new java.awt.Dimension(350, 40));
        sendcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendcodeActionPerformed(evt);
            }
        });
        jPanel9.add(sendcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 90, -1));

        code.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        code.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeActionPerformed(evt);
            }
        });
        jPanel9.add(code, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 230, 40));

        email.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel9.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 330, 40));

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 360));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sendcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendcodeActionPerformed
        String userEmail = email.getText().trim();
        if (userEmail.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter your email.");
            return;
        }
        try {
            config.dbConnector dbc = new config.dbConnector();
            String query = "SELECT * FROM tbl_user WHERE u_email = ?";
            java.sql.PreparedStatement pst = dbc.getConnection().prepareStatement(query);
            pst.setString(1, userEmail);
            java.sql.ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                // Generate reset code and expiry
                String resetCode = config.PwGenerator.generateCode(6);
                java.sql.Timestamp expiry = new java.sql.Timestamp(System.currentTimeMillis() + 15 * 60 * 1000); // 15 minutes expiry

                // Update database with reset code and expiry
                String updateQuery = "UPDATE tbl_user SET reset_code = ?, reset_expiry = ? WHERE u_email = ?";
                java.sql.PreparedStatement updatePst = dbc.getConnection().prepareStatement(updateQuery);
                updatePst.setString(1, resetCode);
                updatePst.setTimestamp(2, expiry);
                updatePst.setString(3, userEmail);
                int updated = updatePst.executeUpdate();
                if (updated > 0) {
                    // Send email with reset code
                    config.EmailSender emailSender = new config.EmailSender();
                    String fromEmail = "padoption73@gmail.com"; // TODO: replace with your email
                    String emailPassword = "ipiz svkj npwb qbue"; // TODO: replace with your email password or app password
                    String subject = "Password Reset Code";
                    String body = "Your password reset code is: " + resetCode + "\nThis code will expire in 15 minutes.";
                    emailSender.sendEmail(fromEmail, emailPassword, userEmail, subject, body);
                    javax.swing.JOptionPane.showMessageDialog(this, "Reset code sent to your email.");
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Failed to set reset code. Please try again.");
                }
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Email not found.");
            }
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error sending reset code: " + ex.getMessage());
        }
    }//GEN-LAST:event_sendcodeActionPerformed

private void verifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyActionPerformed
        String userEmail = email.getText().trim();
        String inputCode = code.getText().trim();
        if (userEmail.isEmpty() || inputCode.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter both email and code.");
            return;
        }
        try {
            config.dbConnector dbc = new config.dbConnector();
            String query = "SELECT reset_code, reset_expiry FROM tbl_user WHERE u_email = ?";
            java.sql.PreparedStatement pst = dbc.getConnection().prepareStatement(query);
            pst.setString(1, userEmail);
            java.sql.ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                String resetCode = rs.getString("reset_code");
                java.sql.Timestamp resetExpiry = rs.getTimestamp("reset_expiry");
                java.sql.Timestamp now = new java.sql.Timestamp(System.currentTimeMillis());
                if (resetCode == null || !resetCode.equals(inputCode)) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Invalid reset code.");
                } else if (resetExpiry == null || resetExpiry.before(now)) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Reset code has expired.");
                } else {
                    // Open forgotpassword form for password reset
                    racazagui.forgotpassword fp = new racazagui.forgotpassword();
                    fp.setEmail(userEmail);
                    fp.setVisible(true);
                    this.dispose();
                }
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Email not found.");
            }
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error verifying reset code: " + ex.getMessage());
        }
    }//GEN-LAST:event_verifyActionPerformed

    private void codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codeActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(emailverification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(emailverification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(emailverification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(emailverification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new emailverification().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField code;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton sendcode;
    private javax.swing.JButton verify;
    // End of variables declaration//GEN-END:variables
}
