/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package racazagui;

import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;


public class forgotpassword extends javax.swing.JFrame {

    private String userEmail;

    public void setEmail(String email) {
        this.userEmail = email;
    }
    
    public forgotpassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        changepassword = new javax.swing.JButton();
        confirmpassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        newpassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(142, 177, 217));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(142, 177, 217));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Reset Password");
        jPanel10.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 500, 40));

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 60));

        changepassword.setBackground(new java.awt.Color(204, 204, 255));
        changepassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        changepassword.setForeground(new java.awt.Color(0, 0, 0));
        changepassword.setText("Change");
        changepassword.setBorder(null);
        changepassword.setPreferredSize(new java.awt.Dimension(350, 40));
        changepassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changepasswordActionPerformed(evt);
            }
        });
        jPanel9.add(changepassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 320, -1));

        confirmpassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel9.add(confirmpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 330, 40));

        jLabel1.setText("Confirm Password");
        jPanel9.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        newpassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel9.add(newpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 330, 40));

        jLabel2.setText("New Password");
        jPanel9.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 360));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void changepasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changepasswordActionPerformed
        String newPassword = new String(newpassword.getPassword());
        String confirmPassword = new String(confirmpassword.getPassword());

        if (newPassword.isEmpty() || confirmPassword.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all password fields.");
            return;
        }

        if (!newPassword.equals(confirmPassword)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Passwords do not match.");
            return;
        }

        try {
            String hashedPassword = config.passwordHasher.hashPassword(newPassword);
            config.dbConnector dbc = new config.dbConnector();
            String updateQuery = "UPDATE tbl_user SET u_password = ?, reset_code = NULL, reset_expiry = NULL WHERE u_email = ?";
            java.sql.PreparedStatement pst = dbc.getConnection().prepareStatement(updateQuery);
            pst.setString(1, hashedPassword);
            pst.setString(2, this.userEmail);
            int updated = pst.executeUpdate();

            if (updated > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Password reset successful.");
                this.dispose();
                new login().setVisible(true);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Failed to reset password. Please try again.");
            }
        } catch (java.sql.SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage());
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(forgotpassword.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_changepasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgotpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgotpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgotpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgotpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgotpassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changepassword;
    private javax.swing.JPasswordField confirmpassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField newpassword;
    // End of variables declaration//GEN-END:variables
}
