    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package racazagui;

import admin.admindashboard;
import config.Logs;
import config.Session;
import config.dbConnector;
import config.passwordHasher;
import java.security.NoSuchAlgorithmException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import user.userDashboard;

/**
 *
 * @author johnlloyd
 */ 
public class login extends javax.swing.JFrame {

    
    public login() {
        initComponents();
        this.setResizable(false);
    }
    
    
    static String status;
    static String type;
    
    
    public static boolean loginAcc(String username,String password){
        dbConnector connector = new dbConnector();
        try{
            String query = "SELECT * FROM tbl_user WHERE u_username = '" + username + "'";  
            ResultSet resultSet = connector.getData(query);
            
          if( resultSet.next()){
              
                String hashedPass = (resultSet.getString("u_password"));    
                String rehashedPass = passwordHasher.hashPassword(password); 
                
                System.out.println(""+ hashedPass);
                System.out.println(""+ rehashedPass);
         if(hashedPass.equals(rehashedPass)){
             status = resultSet.getString("u_status");
            type = resultSet.getString("u_type");
            Session sess = Session.getInstance();
            sess.setUid(resultSet.getInt("u_id"));
            sess.setFname(resultSet.getString("u_firstname"));
            sess.setLname(resultSet.getString("u_lastname"));
            sess.setEmail(resultSet.getString("u_email"));
            sess.setUsername(resultSet.getString("u_username"));
            sess.setType(resultSet.getString("u_type"));
            sess.setStatus(resultSet.getString("u_status"));    
            return true; 
                }else{
                         return false;
                        }
            }else{
                return false;
            }
        }catch (SQLException  | NoSuchAlgorithmException  ex){
            return false;
        }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        background = new javax.swing.JPanel();
        navigation = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pstext = new javax.swing.JLabel();
        ustext = new javax.swing.JLabel();
        loginbutton = new javax.swing.JButton();
        clickheretoregister = new javax.swing.JLabel();
        us = new javax.swing.JTextField();
        ps = new javax.swing.JPasswordField();
        WELCOME3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        forgotpassword = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setForeground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navigation.setBackground(new java.awt.Color(123, 159, 207));
        navigation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/petdefault.png"))); // NOI18N
        navigation.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Love . Care . Protect");
        navigation.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 270, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Support Us!");
        navigation.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 270, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("About Us!");
        navigation.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 270, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Join Us!");
        navigation.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 270, -1));

        background.add(navigation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 590));

        pstext.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pstext.setForeground(new java.awt.Color(0, 0, 0));
        pstext.setText("Password:");
        background.add(pstext, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 90, 40));

        ustext.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ustext.setForeground(new java.awt.Color(0, 0, 0));
        ustext.setText("Username:");
        background.add(ustext, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 90, 40));

        loginbutton.setBackground(new java.awt.Color(204, 204, 255));
        loginbutton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        loginbutton.setText("Login");
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });
        background.add(loginbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 470, 190, 40));

        clickheretoregister.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clickheretoregister.setForeground(new java.awt.Color(0, 0, 0));
        clickheretoregister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clickheretoregister.setText("new user? click here to register.");
        clickheretoregister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickheretoregisterMouseClicked(evt);
            }
        });
        background.add(clickheretoregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 510, 300, 50));

        us.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        us.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        us.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usActionPerformed(evt);
            }
        });
        background.add(us, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 330, 40));

        ps.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        background.add(ps, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 330, 40));

        WELCOME3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        WELCOME3.setForeground(new java.awt.Color(0, 0, 0));
        WELCOME3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WELCOME3.setText("CUDDLE BUDDIES");
        background.add(WELCOME3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 590, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/petdefault.png"))); // NOI18N
        background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, -1, -1));

        forgotpassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        forgotpassword.setForeground(new java.awt.Color(0, 0, 0));
        forgotpassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forgotpassword.setText("Forgot Pasword");
        forgotpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotpasswordMouseClicked(evt);
            }
        });
        background.add(forgotpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 560, 300, -1));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed

        
        
        if(loginAcc(us.getText(),ps.getText())){
           
             
        if(!status.equals("Active")){
      JOptionPane.showMessageDialog(null,"In-Active Account,Contact the Admin!");
     
             
        }else{
      
        if(type.equals("Admin")){
              JOptionPane.showMessageDialog(null,"Login Successfully!");
               Logs.logAction(Session.getInstance().getUid(), "Admin logged in");
              admindashboard ads = new admindashboard();
              ads.setVisible(true);
              this.dispose();
        
        }else if(type.equals("User")){
            Logs.logAction(Session.getInstance().getUid(), "User logged in");

          JOptionPane.showMessageDialog(null,"Login Successfully!");
          userDashboard usd = new userDashboard();
              usd.setVisible(true);
              this.dispose();   
        }else{
      JOptionPane.showMessageDialog(null,"No Account Type Found,Contact the Admin!");
        }
        }
        
        }else{ 
         JOptionPane.showMessageDialog(null,"Invalid Account!");
     }
    }//GEN-LAST:event_loginbuttonActionPerformed

    private void clickheretoregisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickheretoregisterMouseClicked
        
        register rfm = new register();
        rfm.setVisible(true);
        this.dispose();
        


// TODO add your handling code here:
    }//GEN-LAST:event_clickheretoregisterMouseClicked

    private void usActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usActionPerformed

    private void forgotpasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotpasswordMouseClicked
      new emailverification().setVisible(true);
    }//GEN-LAST:event_forgotpasswordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel WELCOME3;
    private javax.swing.JPanel background;
    private javax.swing.JLabel clickheretoregister;
    private javax.swing.JLabel forgotpassword;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton loginbutton;
    private javax.swing.JPanel navigation;
    private javax.swing.JPasswordField ps;
    private javax.swing.JLabel pstext;
    private javax.swing.JTextField us;
    private javax.swing.JLabel ustext;
    // End of variables declaration//GEN-END:variables
}
