/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package racazagui;

import admin.admindashboard;
import config.Session;
import config.dbConnector;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import user.userDashboard;

/**
 *
 * @author johnlloyd
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        this.setResizable(false);
    }
    
    static String status;
    static String type;
    
    
    public static boolean loginAcc(String username,String password){
        dbConnector connector = new dbConnector();
        try{
            String query = "SELECT * FROM tbl_user WHERE u_username = '" + username + "' AND u_password = '" + password + "'";  
            ResultSet resultSet = connector.getData(query);
            if( resultSet.next()){
            status = resultSet.getString("u_status");
            type = resultSet.getString("u_type");
             Session sess = Session.getInstance();
            sess.setUid(resultSet.getInt("u_id"));
            sess.setFname(resultSet.getString("u_firstname"));
            sess.setLname(resultSet.getString("u_lastname"));
            sess.setEmail(resultSet.getString("u_email"));
            sess.setType(resultSet.getString("u_type"));
            sess.setStatus(resultSet.getString("u_status"));

            return true;
            }else{
                return false;
            }
        }catch (SQLException ex){
            return false;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        background = new javax.swing.JPanel();
        navigation = new javax.swing.JPanel();
        WELCOME3 = new javax.swing.JLabel();
        pstext = new javax.swing.JLabel();
        ustext = new javax.swing.JLabel();
        loginbutton = new javax.swing.JButton();
        clickheretoregister = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        us = new javax.swing.JTextField();
        ps = new javax.swing.JPasswordField();

        jCheckBox1.setText("jCheckBox1");

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setForeground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navigation.setBackground(new java.awt.Color(0, 0, 0));
        navigation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WELCOME3.setFont(new java.awt.Font("HP Simplified Jpan", 0, 48)); // NOI18N
        WELCOME3.setForeground(new java.awt.Color(255, 255, 255));
        WELCOME3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WELCOME3.setText("WELCOME TO CUDDLE BUDDIES");
        navigation.add(WELCOME3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 120));

        background.add(navigation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 120));

        pstext.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        pstext.setText("PASSWORD:");
        background.add(pstext, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 120, 50));

        ustext.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ustext.setText("USERNAME:");
        background.add(ustext, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 160, 50));

        loginbutton.setBackground(new java.awt.Color(204, 204, 255));
        loginbutton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        loginbutton.setText("Login");
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });
        background.add(loginbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 500, 230, 50));

        clickheretoregister.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        clickheretoregister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clickheretoregister.setText("new user? click here to register.");
        clickheretoregister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickheretoregisterMouseClicked(evt);
            }
        });
        background.add(clickheretoregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 570, 300, 50));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.jpg"))); // NOI18N
        background.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 120, 590, 580));

        us.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        us.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        us.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usActionPerformed(evt);
            }
        });
        background.add(us, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 450, 50));

        ps.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        background.add(ps, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, 450, 50));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -10, 1020, 710));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed

        
        
        if(loginAcc(us.getText(),ps.getText())){
           
             
        if(!status.equals("Active")){
      JOptionPane.showMessageDialog(null,"In-Active Account,Contact the Admin!");
     
             
        }else{
      
        if(type.equals("Admin")){
              JOptionPane.showMessageDialog(null,"Login Successfully!");
              admindashboard ads = new admindashboard();
              ads.setVisible(true);
              this.dispose();
        
        }else if(type.equals("User")){
          JOptionPane.showMessageDialog(null,"Login Successfully!");
          userDashboard usd = new userDashboard();
              usd.setVisible(true);
              this.dispose();   
        }else{
      JOptionPane.showMessageDialog(null,"No Account Type Found,Contact the Admin!");
        }
        }
        
        }else{ 
         JOptionPane.showMessageDialog(null,"Invalid Account!");
     }
    }//GEN-LAST:event_loginbuttonActionPerformed

    private void clickheretoregisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickheretoregisterMouseClicked
        
        register rfm = new register();
        rfm.setVisible(true);
        this.dispose();
        


// TODO add your handling code here:
    }//GEN-LAST:event_clickheretoregisterMouseClicked

    private void usActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel WELCOME3;
    private javax.swing.JPanel background;
    private javax.swing.JLabel clickheretoregister;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JButton loginbutton;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel navigation;
    private javax.swing.JPasswordField ps;
    private javax.swing.JLabel pstext;
    private javax.swing.JTextField us;
    private javax.swing.JLabel ustext;
    // End of variables declaration//GEN-END:variables
}
