/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package racazagui;


import admin.usersForm;
import config.dbConnector;
import config.passwordHasher;
import java.security.NoSuchAlgorithmException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author johnlloyd
 */
public class register extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    public register() {
        initComponents();
    }
        public static String email,usname;
        
       public boolean duplicateCheck(){
           dbConnector dbc = new dbConnector();
           try{String query = "SELECT * FROM tbl_user WHERE u_username = '" + us.getText() + "' OR u_password = '" + em.getText() + "'";  
            ResultSet resultSet = dbc.getData(query);
            if(resultSet.next()){
               email = resultSet.getString("u_email");
                if(email.equals(em.getText())){
                    JOptionPane.showMessageDialog(null, "Email is Already used");
                    em.setText("");
                }
               usname = resultSet.getString("u_username");
               System.out.println(""+usname);
                if(usname.equals(us.getText())){
                    JOptionPane.showMessageDialog(null, "Username is Already used");
                    us.setText("");
                }
                return true;
            }else{
                return false;
            }
           }catch(SQLException ex){
               System.out.println(""+ex);
               return false;
       }
    
       }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new javax.swing.JPanel();
        attext1 = new javax.swing.JLabel();
        resfntext1 = new javax.swing.JLabel();
        reslntext1 = new javax.swing.JLabel();
        resemailtext1 = new javax.swing.JLabel();
        resusrntext1 = new javax.swing.JLabel();
        fn = new javax.swing.JTextField();
        em = new javax.swing.JTextField();
        ln = new javax.swing.JTextField();
        resloginbutton = new javax.swing.JButton();
        resps2 = new javax.swing.JLabel();
        us = new javax.swing.JTextField();
        at = new javax.swing.JComboBox<>();
        ps = new javax.swing.JPasswordField();
        lll1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        navigation2 = new javax.swing.JPanel();
        registrationformtext2 = new javax.swing.JLabel();
        WELCOME4 = new javax.swing.JLabel();
        recancelbutton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background1.setBackground(new java.awt.Color(142, 177, 217));
        background1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        attext1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        attext1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        attext1.setText("Account Type:");
        background1.add(attext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 460, 330, 40));

        resfntext1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        resfntext1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resfntext1.setText("First Name:");
        background1.add(resfntext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 330, 40));

        reslntext1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        reslntext1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reslntext1.setText("Last Name:");
        background1.add(reslntext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 330, 40));

        resemailtext1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        resemailtext1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resemailtext1.setText("Email:");
        background1.add(resemailtext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 330, 40));

        resusrntext1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        resusrntext1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resusrntext1.setText("Username:");
        background1.add(resusrntext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 330, 40));

        fn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        fn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnActionPerformed(evt);
            }
        });
        background1.add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 330, 40));

        em.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        em.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        em.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emActionPerformed(evt);
            }
        });
        background1.add(em, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 330, 40));

        ln.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ln.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnActionPerformed(evt);
            }
        });
        background1.add(ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 330, 40));

        resloginbutton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        resloginbutton.setText("Register");
        resloginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resloginbuttonActionPerformed(evt);
            }
        });
        background1.add(resloginbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 660, 130, 50));

        resps2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        resps2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resps2.setText("Password:");
        background1.add(resps2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 330, 40));

        us.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        us.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        us.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usActionPerformed(evt);
            }
        });
        background1.add(us, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 330, 40));

        at.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        at.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User", "Admin" }));
        at.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atActionPerformed(evt);
            }
        });
        background1.add(at, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, 330, 50));

        ps.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psActionPerformed(evt);
            }
        });
        background1.add(ps, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, 330, 40));

        lll1.setBackground(new java.awt.Color(123, 159, 207));
        lll1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/supp logo (1)-modified.png"))); // NOI18N
        lll1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Love . Care . Protect");
        lll1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 270, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Support Us!");
        lll1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 270, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("About Us!");
        lll1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 270, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Join Us!");
        lll1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 270, -1));

        navigation2.setBackground(new java.awt.Color(123, 159, 207));
        navigation2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registrationformtext2.setFont(new java.awt.Font("HP Simplified Jpan", 0, 48)); // NOI18N
        registrationformtext2.setForeground(new java.awt.Color(255, 255, 255));
        registrationformtext2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registrationformtext2.setText("REGISTRATION FORM");
        navigation2.add(registrationformtext2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, 20, 1000, 60));

        lll1.add(navigation2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -90, 1000, 140));

        background1.add(lll1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 740));

        WELCOME4.setFont(new java.awt.Font("HP Simplified Jpan", 0, 36)); // NOI18N
        WELCOME4.setForeground(new java.awt.Color(255, 255, 255));
        WELCOME4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WELCOME4.setText("Register Form");
        background1.add(WELCOME4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 620, 80));

        recancelbutton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        recancelbutton.setText("Cancel");
        recancelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recancelbuttonActionPerformed(evt);
            }
        });
        background1.add(recancelbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 660, 130, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(background1, javax.swing.GroupLayout.PREFERRED_SIZE, 877, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void resloginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resloginbuttonActionPerformed
            
        if(fn.getText().isEmpty()||ln.getText().isEmpty()
                ||em.getText().isEmpty()||us.getText().isEmpty()
                ||ps.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "All fields are required!");
        }else if (ps.getText().length() < 8) {
        JOptionPane.showMessageDialog(null, "Password must be at least 8 characters long");
        ps.setText("");
        }else if(duplicateCheck()){
            System.out.println("Duplicate Exist");
               
        }else{ 
            dbConnector dbc = new dbConnector();
            try{
            String pass = passwordHasher.hashPassword(ps.getText());
            
            if(dbc.insertData("INSERT INTO tbl_user (u_firstname, u_lastname, u_email,"
                + " u_username, u_password, u_type, u_status) "
                + "VALUES ('"+ fn.getText() + "','" + ln.getText() + "','" + em.getText()
                + "','" + us.getText() + "','" + pass + "','" +
                at.getSelectedItem() + "','Pending')")>0){
            
            
        
           JOptionPane.showMessageDialog(null, "Registraation Succes!"); 
           login lg = new login();
           lg.setVisible(true);
           this.dispose(); 
        }else {
                JOptionPane.showMessageDialog(null, "Connection Error!"); 
                }
            }catch(NoSuchAlgorithmException ex){
                System.out.println(""+ex);
            }
    }//GEN-LAST:event_resloginbuttonActionPerformed
  
    }
    private void rescancelbutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rescancelbutton2ActionPerformed
new login().setVisible(true);
this.dispose();
    }//GEN-LAST:event_rescancelbutton2ActionPerformed

    private void fnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnActionPerformed
    String firstName = fn.getText();  // ✅ Correct
       
    }//GEN-LAST:event_fnActionPerformed

    private void lnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnActionPerformed
    String lastName = ln.getText();  // ✅ Correct
    }//GEN-LAST:event_lnActionPerformed

    private void emActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emActionPerformed
  String email = em.getText().trim();  // ✅ Correct              
         dbConnector dbc = new dbConnector();       
    }//GEN-LAST:event_emActionPerformed
    
       
    private void usActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usActionPerformed
       String username = us.getText();  // ✅ Correct
      
       if (username.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Username is required!");
        return;
    }
    dbConnector dbc = new dbConnector();
    
    }//GEN-LAST:event_usActionPerformed

    private void atActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atActionPerformed

    private void psActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psActionPerformed
     String password = ps.getText();  // 
    }//GEN-LAST:event_psActionPerformed

    private void recancelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recancelbuttonActionPerformed
       login lg = new login();
           lg.setVisible(true);
           this.dispose(); 
    }//GEN-LAST:event_recancelbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel WELCOME4;
    private javax.swing.JComboBox<String> at;
    private javax.swing.JLabel attext1;
    private javax.swing.JPanel background1;
    private javax.swing.JTextField em;
    private javax.swing.JTextField fn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel lll1;
    private javax.swing.JTextField ln;
    private javax.swing.JPanel navigation2;
    private javax.swing.JPasswordField ps;
    private javax.swing.JToggleButton recancelbutton;
    private javax.swing.JLabel registrationformtext2;
    private javax.swing.JLabel resemailtext1;
    private javax.swing.JLabel resfntext1;
    private javax.swing.JLabel reslntext1;
    private javax.swing.JButton resloginbutton;
    private javax.swing.JLabel resps2;
    private javax.swing.JLabel resusrntext1;
    private javax.swing.JTextField us;
    // End of variables declaration//GEN-END:variables
}
