/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package racazagui;


import config.dbConnector;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author johnlloyd
 */
public class register extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    public register() {
        initComponents();
    }
        public static String email,usname;
        
       public boolean duplicateCheck(){
           dbConnector dbc = new dbConnector();
           try{String query = "SELECT * FROM tbl_user WHERE u_username = '" + us.getText() + "' OR u_password = '" + em.getText() + "'";  
            ResultSet resultSet = dbc.getData(query);
            if(resultSet.next()){
               email = resultSet.getString("u_email");
                if(email.equals(em.getText())){
                    JOptionPane.showMessageDialog(null, "Email is Already used");
                    em.setText("");
                }
               usname = resultSet.getString("u_username");
               System.out.println(""+usname);
                if(usname.equals(us.getText())){
                    JOptionPane.showMessageDialog(null, "Username is Already used");
                    us.setText("");
                }
                return true;
            }else{
                return false;
            }
           }catch(SQLException ex){
               System.out.println(""+ex);
               return false;
       }
    
       }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        background = new javax.swing.JPanel();
        rgnavigation = new javax.swing.JPanel();
        registrationformtext = new javax.swing.JLabel();
        attext = new javax.swing.JLabel();
        resfntext = new javax.swing.JLabel();
        ps = new javax.swing.JTextField();
        reslntext = new javax.swing.JLabel();
        resemailtext = new javax.swing.JLabel();
        resusrntext = new javax.swing.JLabel();
        fn = new javax.swing.JTextField();
        em = new javax.swing.JTextField();
        ln = new javax.swing.JTextField();
        resloginbutton = new javax.swing.JButton();
        rescancelbutton2 = new javax.swing.JButton();
        resps1 = new javax.swing.JLabel();
        logo1 = new javax.swing.JLabel();
        us = new javax.swing.JTextField();
        at = new javax.swing.JComboBox<>();

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rgnavigation.setBackground(new java.awt.Color(0, 0, 0));
        rgnavigation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registrationformtext.setFont(new java.awt.Font("HP Simplified Jpan", 0, 48)); // NOI18N
        registrationformtext.setForeground(new java.awt.Color(255, 255, 255));
        registrationformtext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registrationformtext.setText("REGISTRATION FORM");
        rgnavigation.add(registrationformtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 110));

        background.add(rgnavigation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 110));

        attext.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        attext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        attext.setText("Account Type:");
        background.add(attext, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 510, 450, 40));

        resfntext.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        resfntext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resfntext.setText("First Name:");
        background.add(resfntext, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 450, 40));

        ps.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ps.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psActionPerformed(evt);
            }
        });
        background.add(ps, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, 450, 40));

        reslntext.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        reslntext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reslntext.setText("Last Name:");
        background.add(reslntext, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 450, 40));

        resemailtext.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        resemailtext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resemailtext.setText("Email:");
        background.add(resemailtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 450, 40));

        resusrntext.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        resusrntext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resusrntext.setText("Username:");
        background.add(resusrntext, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, 450, 40));

        fn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        fn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnActionPerformed(evt);
            }
        });
        background.add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 450, 40));

        em.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        em.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        em.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emActionPerformed(evt);
            }
        });
        background.add(em, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 450, 40));

        ln.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ln.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnActionPerformed(evt);
            }
        });
        background.add(ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 450, 40));

        resloginbutton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        resloginbutton.setText("Register");
        resloginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resloginbuttonActionPerformed(evt);
            }
        });
        background.add(resloginbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 640, 160, 60));

        rescancelbutton2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rescancelbutton2.setText("Cancel");
        rescancelbutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rescancelbutton2ActionPerformed(evt);
            }
        });
        background.add(rescancelbutton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 640, 160, 60));

        resps1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        resps1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resps1.setText("Password:");
        background.add(resps1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, 450, 40));

        logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.jpg"))); // NOI18N
        background.add(logo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 110, 620, 620));

        us.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        us.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        us.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usActionPerformed(evt);
            }
        });
        background.add(us, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, 450, 40));

        at.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        at.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User", "Admin" }));
        at.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atActionPerformed(evt);
            }
        });
        background.add(at, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 550, 450, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 733, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void resloginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resloginbuttonActionPerformed
            
        if(fn.getText().isEmpty()||ln.getText().isEmpty()
                ||em.getText().isEmpty()||us.getText().isEmpty()
                ||ps.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "All fields are required!");
        }else if (ps.getText().length() < 8) {
        JOptionPane.showMessageDialog(null, "Password must be at least 8 characters long");
        ps.setText("");
        }else if(duplicateCheck()){
            System.out.println("Duplicate Exist");
               
        }else{ 
            dbConnector dbc = new dbConnector();
            if(dbc.insertData("INSERT INTO tbl_user (u_firstname, u_lastname, u_email,"
                + " u_username, u_password, u_type, u_status) "
                + "VALUES ('"+ fn.getText() + "','" + ln.getText() + "','" + em.getText()
                + "','" + us.getText() + "','" + ps.getText() + "','" +
                at.getSelectedItem() + "','Pending')")>0){
            
            
        
           JOptionPane.showMessageDialog(null, "Registraation Succes!"); 
           login lg = new login();
           lg.setVisible(true);
           this.dispose(); 
        }else {
                JOptionPane.showMessageDialog(null, "Connection Error!"); 
                }
    }//GEN-LAST:event_resloginbuttonActionPerformed
  
    }
    private void rescancelbutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rescancelbutton2ActionPerformed
  
    }//GEN-LAST:event_rescancelbutton2ActionPerformed

    private void fnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnActionPerformed
    String firstName = fn.getText();  // ✅ Correct
       
    }//GEN-LAST:event_fnActionPerformed

    private void lnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnActionPerformed
    String lastName = ln.getText();  // ✅ Correct
    }//GEN-LAST:event_lnActionPerformed

    private void psActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psActionPerformed
        
          String password = ps.getText();  // ✅ Correct
        
    }//GEN-LAST:event_psActionPerformed

    private void emActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emActionPerformed
  String email = em.getText().trim();  // ✅ Correct              
         dbConnector dbc = new dbConnector();       
    }//GEN-LAST:event_emActionPerformed
    
       
    private void usActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usActionPerformed
       String username = us.getText();  // ✅ Correct
      
       if (username.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Username is required!");
        return;
    }
    dbConnector dbc = new dbConnector();
    
    }//GEN-LAST:event_usActionPerformed

    private void atActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> at;
    private javax.swing.JLabel attext;
    private javax.swing.JPanel background;
    private javax.swing.JTextField em;
    private javax.swing.JTextField fn;
    private javax.swing.JTextField ln;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logo1;
    private javax.swing.JTextField ps;
    private javax.swing.JLabel registrationformtext;
    private javax.swing.JButton rescancelbutton2;
    private javax.swing.JLabel resemailtext;
    private javax.swing.JLabel resfntext;
    private javax.swing.JLabel reslntext;
    private javax.swing.JButton resloginbutton;
    private javax.swing.JLabel resps1;
    private javax.swing.JLabel resusrntext;
    private javax.swing.JPanel rgnavigation;
    private javax.swing.JTextField us;
    // End of variables declaration//GEN-END:variables
}
