/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import config.Session;
import javax.swing.JOptionPane;
import racazagui.login;

/**
 *
 * @author johnlloyd
 */
public class admindashboard extends javax.swing.JFrame {

    /**
     * Creates new form admindashboard
     */
    public admindashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        navigation = new javax.swing.JPanel();
        aa = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        acc_lname = new javax.swing.JLabel();
        acc_fname = new javax.swing.JLabel();
        userstable = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        navigation1 = new javax.swing.JPanel();
        WELCOME4 = new javax.swing.JLabel();
        lgo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navigation.setBackground(new java.awt.Color(0, 0, 0));
        navigation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aa.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add-removebg-preview (1).png"))); // NOI18N
        aa.add(jLabel1);

        acc_lname.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        acc_lname.setForeground(new java.awt.Color(255, 255, 255));
        acc_lname.setText("ADMIN");
        aa.add(acc_lname);

        acc_fname.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        acc_fname.setForeground(new java.awt.Color(255, 255, 255));
        acc_fname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_fname.setText("ADMIN");
        aa.add(acc_fname);

        navigation.add(aa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 180, 270));

        jPanel1.add(navigation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 260, 630));

        userstable.setBackground(new java.awt.Color(255, 255, 255));
        userstable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userstableMouseClicked(evt);
            }
        });
        userstable.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("USERS");
        userstable.add(jLabel2);
        jLabel2.setBounds(60, 140, 80, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user11-removebg-preview.png"))); // NOI18N
        userstable.add(jLabel4);
        jLabel4.setBounds(0, 30, 190, 110);

        jPanel1.add(userstable, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 190, 180));

        navigation1.setBackground(new java.awt.Color(0, 0, 0));
        navigation1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WELCOME4.setFont(new java.awt.Font("HP Simplified Jpan", 0, 36)); // NOI18N
        WELCOME4.setForeground(new java.awt.Color(255, 255, 255));
        WELCOME4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WELCOME4.setText("ADMIN DASHBOARD");
        navigation1.add(WELCOME4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 330, 70));

        lgo.setBackground(new java.awt.Color(255, 255, 255));
        lgo.setFont(new java.awt.Font("HP Simplified Jpan", 0, 24)); // NOI18N
        lgo.setForeground(new java.awt.Color(255, 255, 255));
        lgo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lgo.setText("LOGOUT");
        lgo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lgoMouseClicked(evt);
            }
        });
        navigation1.add(lgo, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 20, 120, 70));

        jPanel1.add(navigation1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1150, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1030, 690));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userstableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userstableMouseClicked
        usersForm usf  = new usersForm();
        usf.setVisible(true);
        this.dispose();           
    }//GEN-LAST:event_userstableMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       Session sess = Session.getInstance();
       if(sess.getUid()==0){
         JOptionPane.showMessageDialog(null,"No Account, Log in First!");
           login lg = new login ();
         lg.setVisible(true);
         this.dispose();       
       }else {
           acc_fname.setText(""+sess.getFname());
           acc_lname.setText(""+sess.getLname());
       }
    }//GEN-LAST:event_formWindowActivated

    private void lgoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgoMouseClicked
 new login().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_lgoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admindashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admindashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admindashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admindashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admindashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel WELCOME4;
    private javax.swing.JPanel aa;
    private javax.swing.JLabel acc_fname;
    private javax.swing.JLabel acc_lname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lgo;
    private javax.swing.JPanel navigation;
    private javax.swing.JPanel navigation1;
    private javax.swing.JPanel userstable;
    // End of variables declaration//GEN-END:variables
}
